# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-19 06:15
from __future__ import unicode_literals

import biocombat.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioCard',
            fields=[
                ('hp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(40)])),
                ('structure', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(45)])),
                ('image', models.ImageField(upload_to=biocombat.models.renameImage)),
                ('info', models.CharField(max_length=330, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(330)])),
                ('atk', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cardType', models.IntegerField(choices=[(0, b'Defense Mechanism'), (1, b'Bacteria'), (2, b'Other Mechanisms')])),
            ],
        ),
    ]
