# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-30 08:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocombat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biocard',
            name='atk',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='biocard',
            name='hp',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
